version: '3'

services:
  db:
    container_name: my_custon_sql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'daniel'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'daniel'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'linux123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./database:/var/lib/mysql

# Names our volume
volumes:
  my-db:

