version: '3.9'

services:
  #This is the server name
  mysql_db:
    container_name: mysql_custom
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'superPass' # Password for root access
      MYSQL_DATABASE: 'db' #Database name
      MYSQL_USER: 'user' # So you don't have to use root, but you can if you like      
      MYSQL_PASSWORD: 'passUser' # You can use whatever password you like      

    # <Port exposed>:<MySQL Port running inside container>
    ports:       
      - '3306:3306'
  
  myAdmin:
    container_name: php_my_admin
    image: phpmyadmin:5.2.0
    links:
      - mysql_db
    environment:
      PMA_HOST: 'db'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - mysql_db

#To use volumes instead folder inside the project root
#The name of the volume will be: <projectName>_<volumeName>
volumes:
  mysql-data:
